//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewTestTemplatev2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrEmployee
    {
        public int ID { get; set; }
        public string FistName { get; set; }
        public string SecondName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int HrDepartmentId { get; set; }
        public string JobTitle { get; set; }
        public int Salary { get; set; }
        public string Full_Name { get; set; }
    }
}
